title: Warwick Cyber Security Society
description: Welcome to the Warwick Cyber Security Society!. We're a friendly and
  inclusive community centred around our love of Cyber Security.
discordURL: https://discord.gg/Ys4fr5CMKj
instagramURL: https://www.instagram.com/warwickcybersoc/
twitterURL: https://twitter.com/warwickcybersoc
githubURL: https://www.github.com/warwickcybersoc/
societyURL: https://www.warwicksu.com/societies-sports/societies/61481/
email: contact@warwickcybersoc.com
exec:
- name: Ellis Trisk-Grove
  image: ellis.jpg
  role: President
  enabled: false
- name: Oscar Sharpe
  image: oscars.jpg
  role: Vice President
  enabled: false
- name: Jamie Madden
  image: blank.png
  role: Treasurer
  enabled: false
- name: Oscar Innes
  image: oscari.jpg
  role: Welfare Officer
  enabled: false
- name: Tom Steer
  image: toms.jpg
  role: Technician
  enabled: false
- name: Abi Lowrie
  image: blank.png
  role: Women's Officer
  enabled: false
- name: Peter Walker
  image: peterw.jpg
  role: External Communications Officer
  enabled: false
navbar:
- name: Home
  link: /
- name: Events
  link: /events
- name: Resources
  link: /resources
achievements:
- title: '#2 - pwnEd5 CTF (2024)'
  year: "2024"
- title: '#1 - pwnEd2 CTF (2021)'
  year: "2021"
- title: '#1 - HTB x UNI CTF Qualifiers (2021)'
  year: "2021"
- title: '#1 - Veracode The Hacker Games (2021)'
  year: "2021"
googleCalendarAPIKey: AIzaSyB4zs2Pj-03aUlL5CHiRwU-PYVZR8glej0
googleCalendarID: cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a@group.calendar.google.com
googleCalendarURL: https://calendar.google.com/calendar/embed?src=cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a%40group.calendar.google.com&ctz=Europe%2FLondon
posts:
- title: Intake CTF 2023
  author: Tom Steer
  link: https://tomsteer.com/posts/intakectf/
- title: Intake 2023 Writeups
  author: Oscar Sharpe
  link: https://oscarsharpe.me/posts/intake-writeup
resources:
- title: Warwick Cyber Security Society GitHub
  link: https://github.com/WarwickCyberSoc
  description: Our GitHub repository, where we store all of our resources and write-ups.
